[package]
name = "foo_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eternaltwin_core = { version = "0.1.0" }
eternaltwin_config = { version = "0.1.0", path = "../eternaltwin_config" }
